// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetBadgesByLogin implements getBadgesByLogin operation.
//
// Returns a list of participant badges by login.
//
// GET /v1/participants/{login}/badges
func (UnimplementedHandler) GetBadgesByLogin(ctx context.Context, params GetBadgesByLoginParams) (r GetBadgesByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCampuses implements getCampuses operation.
//
// Returns a list of campuses.
//
// GET /v1/campuses
func (UnimplementedHandler) GetCampuses(ctx context.Context) (r GetCampusesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClustersByCampus implements getClustersByCampus operation.
//
// Returns a list of clusters in a campus by ID.
//
// GET /v1/campuses/{campusId}/clusters
func (UnimplementedHandler) GetClustersByCampus(ctx context.Context, params GetClustersByCampusParams) (r GetClustersByCampusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCoalitionByLogin implements getCoalitionByLogin operation.
//
// Returns participant coalition information by login.
//
// GET /v1/participants/{login}/coalition
func (UnimplementedHandler) GetCoalitionByLogin(ctx context.Context, params GetCoalitionByLoginParams) (r GetCoalitionByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCoalitionsByCampus implements getCoalitionsByCampus operation.
//
// Returns a list of coalitions in a campus by ID.
//
// GET /v1/campuses/{campusId}/coalitions
func (UnimplementedHandler) GetCoalitionsByCampus(ctx context.Context, params GetCoalitionsByCampusParams) (r GetCoalitionsByCampusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCourseByCourseId implements getCourseByCourseId operation.
//
// Returns course information by ID.
//
// GET /v1/courses/{courseId}
func (UnimplementedHandler) GetCourseByCourseId(ctx context.Context, params GetCourseByCourseIdParams) (r GetCourseByCourseIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEvents implements getEvents operation.
//
// Returns a list of events.
//
// GET /v1/events
func (UnimplementedHandler) GetEvents(ctx context.Context, params GetEventsParams) (r GetEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGraph implements getGraph operation.
//
// Returns a participant projects map.
//
// GET /v1/graph
func (UnimplementedHandler) GetGraph(ctx context.Context) (r GetGraphRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLogWeeklyAvgHoursByLoginAndDate implements getLogWeeklyAvgHoursByLoginAndDate operation.
//
// Returns an average week logtime by login.
//
// GET /v1/participants/{login}/logtime
func (UnimplementedHandler) GetLogWeeklyAvgHoursByLoginAndDate(ctx context.Context, params GetLogWeeklyAvgHoursByLoginAndDateParams) (r GetLogWeeklyAvgHoursByLoginAndDateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLoginsByProjectId implements getLoginsByProjectId operation.
//
// Returns a list of participants by project ID.
//
// GET /v1/projects/{projectId}/participants
func (UnimplementedHandler) GetLoginsByProjectId(ctx context.Context, params GetLoginsByProjectIdParams) (r GetLoginsByProjectIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantByLogin implements getParticipantByLogin operation.
//
// Returns basic participant information by login.
//
// GET /v1/participants/{login}
func (UnimplementedHandler) GetParticipantByLogin(ctx context.Context, params GetParticipantByLoginParams) (r GetParticipantByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantCourseByLoginAndCourseId implements getParticipantCourseByLoginAndCourseId operation.
//
// Returns participant course information by ID.
//
// GET /v1/participants/{login}/courses/{courseId}
func (UnimplementedHandler) GetParticipantCourseByLoginAndCourseId(ctx context.Context, params GetParticipantCourseByLoginAndCourseIdParams) (r GetParticipantCourseByLoginAndCourseIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantCoursesByLogin implements getParticipantCoursesByLogin operation.
//
// Returns participant courses information by login.
//
// GET /v1/participants/{login}/courses
func (UnimplementedHandler) GetParticipantCoursesByLogin(ctx context.Context, params GetParticipantCoursesByLoginParams) (r GetParticipantCoursesByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantFeedbackByLogin implements getParticipantFeedbackByLogin operation.
//
// Returns average participant feedback points by login.
//
// GET /v1/participants/{login}/feedback
func (UnimplementedHandler) GetParticipantFeedbackByLogin(ctx context.Context, params GetParticipantFeedbackByLoginParams) (r GetParticipantFeedbackByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantProjectByLoginAndProjectId implements getParticipantProjectByLoginAndProjectId operation.
//
// Returns participant project information by ID.
//
// GET /v1/participants/{login}/projects/{projectId}
func (UnimplementedHandler) GetParticipantProjectByLoginAndProjectId(ctx context.Context, params GetParticipantProjectByLoginAndProjectIdParams) (r GetParticipantProjectByLoginAndProjectIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantProjectsByLogin implements getParticipantProjectsByLogin operation.
//
// Returns participant projects information by login.
//
// GET /v1/participants/{login}/projects
func (UnimplementedHandler) GetParticipantProjectsByLogin(ctx context.Context, params GetParticipantProjectsByLoginParams) (r GetParticipantProjectsByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantWorkstationByLogin implements getParticipantWorkstationByLogin operation.
//
// Returns a participant workstation by login.
//
// GET /v1/participants/{login}/workstation
func (UnimplementedHandler) GetParticipantWorkstationByLogin(ctx context.Context, params GetParticipantWorkstationByLoginParams) (r GetParticipantWorkstationByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantsByCampusId implements getParticipantsByCampusId operation.
//
// Returns a list of participants in a campus by ID.
//
// GET /v1/campuses/{campusId}/participants
func (UnimplementedHandler) GetParticipantsByCampusId(ctx context.Context, params GetParticipantsByCampusIdParams) (r GetParticipantsByCampusIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantsByCoalitionId implements getParticipantsByCoalitionId operation.
//
// Returns a list of participants in a coalition by ID.
//
// GET /v1/coalitions/{coalitionId}/participants
func (UnimplementedHandler) GetParticipantsByCoalitionId(ctx context.Context, params GetParticipantsByCoalitionIdParams) (r GetParticipantsByCoalitionIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParticipantsByCoalitionId1 implements getParticipantsByCoalitionId_1 operation.
//
// Returns a cluster map.
//
// GET /v1/clusters/{clusterId}/map
func (UnimplementedHandler) GetParticipantsByCoalitionId1(ctx context.Context, params GetParticipantsByCoalitionId1Params) (r GetParticipantsByCoalitionId1Res, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPointsByLogin implements getPointsByLogin operation.
//
// Returns participant points information by login.
//
// GET /v1/participants/{login}/points
func (UnimplementedHandler) GetPointsByLogin(ctx context.Context, params GetPointsByLoginParams) (r GetPointsByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectByProjectId implements getProjectByProjectId operation.
//
// Returns project information by ID.
//
// GET /v1/projects/{projectId}
func (UnimplementedHandler) GetProjectByProjectId(ctx context.Context, params GetProjectByProjectIdParams) (r GetProjectByProjectIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSales implements getSales operation.
//
// Returns current sales’ statuses within parallel.
//
// GET /v1/sales
func (UnimplementedHandler) GetSales(ctx context.Context) (r GetSalesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSoftSkillByLogin implements getSoftSkillByLogin operation.
//
// Returns participant skill points by login.
//
// GET /v1/participants/{login}/skills
func (UnimplementedHandler) GetSoftSkillByLogin(ctx context.Context, params GetSoftSkillByLoginParams) (r GetSoftSkillByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetXpHistoryByLogin implements getXpHistoryByLogin operation.
//
// Returns a list of participant XP accruals by login.
//
// GET /v1/participants/{login}/experience-history
func (UnimplementedHandler) GetXpHistoryByLogin(ctx context.Context, params GetXpHistoryByLoginParams) (r GetXpHistoryByLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}
