// Code generated by ogen, DO NOT EDIT.
package api

type GetBadgesByLoginRes interface {
	getBadgesByLoginRes()
}

type GetCampusesRes interface {
	getCampusesRes()
}

type GetClustersByCampusRes interface {
	getClustersByCampusRes()
}

type GetCoalitionByLoginRes interface {
	getCoalitionByLoginRes()
}

type GetCoalitionsByCampusRes interface {
	getCoalitionsByCampusRes()
}

type GetCourseByCourseIdRes interface {
	getCourseByCourseIdRes()
}

type GetEventsRes interface {
	getEventsRes()
}

type GetGraphRes interface {
	getGraphRes()
}

type GetLogWeeklyAvgHoursByLoginAndDateRes interface {
	getLogWeeklyAvgHoursByLoginAndDateRes()
}

type GetLoginsByProjectIdRes interface {
	getLoginsByProjectIdRes()
}

type GetParticipantByLoginRes interface {
	getParticipantByLoginRes()
}

type GetParticipantCourseByLoginAndCourseIdRes interface {
	getParticipantCourseByLoginAndCourseIdRes()
}

type GetParticipantCoursesByLoginRes interface {
	getParticipantCoursesByLoginRes()
}

type GetParticipantFeedbackByLoginRes interface {
	getParticipantFeedbackByLoginRes()
}

type GetParticipantProjectByLoginAndProjectIdRes interface {
	getParticipantProjectByLoginAndProjectIdRes()
}

type GetParticipantProjectsByLoginRes interface {
	getParticipantProjectsByLoginRes()
}

type GetParticipantWorkstationByLoginRes interface {
	getParticipantWorkstationByLoginRes()
}

type GetParticipantsByCampusIdRes interface {
	getParticipantsByCampusIdRes()
}

type GetParticipantsByCoalitionId1Res interface {
	getParticipantsByCoalitionId1Res()
}

type GetParticipantsByCoalitionIdRes interface {
	getParticipantsByCoalitionIdRes()
}

type GetPointsByLoginRes interface {
	getPointsByLoginRes()
}

type GetProjectByProjectIdRes interface {
	getProjectByProjectIdRes()
}

type GetSalesRes interface {
	getSalesRes()
}

type GetSoftSkillByLoginRes interface {
	getSoftSkillByLoginRes()
}

type GetXpHistoryByLoginRes interface {
	getXpHistoryByLoginRes()
}
